const émotions = {
      Joie: [
        "🌸Sourate Yunus (10:58):« Dis : 'C'est par la grâce d'Allah et Sa miséricorde que les gens doivent se réjouir.'»🌸",
        "🌸Sourate Al-Baqara (2:261):« Ceux qui dépensent leurs biens dans le sentier d'Allah sont comme une graine qui fait pousser sept épis, multipliant leur joie.»🌸",
        "🌸Sourate Al-Imran (3:139):« Ne faiblissez pas et ne soyez pas attristés ; vous êtes supérieurs si vous êtes croyants.»🌸",
        "🌸Sourate Ash-Sharh (94:5-6):« A côté de la difficulté est, certes, une facilité.A côté de la difficulté est, certes, une facilité.»🌸",
        "🌸Sourate Al-An'am (6:141):« Et mangez des fruits et des bestiaux que vous a accordés Allah, comme source de joie et de gratitude.»🌸",
        "🌸Sourate Al-Furqan (25:74):« Seigneur, accorde-nous de nos épouses et de nos enfants la joie de nos yeux.»🌸",
        "🌸Sourate Ar-Rum (30:21):« Et parmi Ses signes : Il a créé pour vous des épouses afin que vous trouviez auprès delles tranquillité et bonheur.»🌸",
        "🌸Sourate  Al-Ma'idah (5:114):« Seigneur, fais descendre sur nous un repas du ciel ».🌸",
        "🌸Sourate Al-A'raf (7:43):« Nous les ferons entrer dans des Jardins où coulent les rivières.»🌸",
        "🌸Sourate Al-Baqara (2:152):« Rappelez-vous de Moi, Je Me rappellerai de vous. »🌸",
      ],
      Anxiété: [
        "🌸Sourate Al-Baqara (2:286): « Allah n'impose à aucune âme une charge supérieure à sa capacité.»🌸",
        "🌸Sourate At-Tawbah (9:51): « Dis : Rien ne nous atteindra, sauf ce qu'Allah a prescrit pour nous. Il est notre Protecteur.»🌸",
        "🌸Sourate Al-Anfal (8:2): « Les vrais croyants sont ceux dont les cœurs frémissent quand on mentionne Allah, et quand Ses versets leur sont récités, cela fait croître leur foi.»🌸",
        "🌸Sourate Ar-Ra'd (13:28): « N'est-ce point par l'évocation d'Allah que se tranquillisent les cœurs ?»🌸",
        "🌸Sourate Yunus (10:62): « En vérité, les bien-aimés d'Allah seront à l'abri de toute crainte, et ils ne seront point affligés.»🌸",
        "🌸Sourate Al-Imran (3:139): « Ne faiblissez pas et ne vous affligez pas, alors que vous êtes les supérieurs, si vous êtes croyants.»🌸",
        "🌸Sourate Ash-Sharh (94:5-6): « A côté de la difficulté est, certes, une facilité. A côté de la difficulté est, certes, une facilité.»🌸",
        "🌸Sourate Al-Baqara (2:153): « Ô vous qui avez cru ! Cherchez secours dans l'endurance et la prière. Car Allah est avec ceux qui sont patients.»🌸",
        "🌸Sourate Al-Ankabut (29:69): « Et quant à ceux qui luttent pour Notre cause, Nous les guiderons certes sur Nos sentiers.»🌸",
        "🌸Sourate At-Talaq (65:2-3): « Quiconque craint Allah, Il lui donnera une issue favorable, et lui accordera sa subsistance d'où il ne s'y attend pas.»🌸",
      ],
      Colère: [
        "🌸Sourate Al-Imran (3:134): « Ceux qui dépensent dans l'aisance et dans l'adversité, qui dominent leur rage et pardonnent aux gens-et Allah aime les bienfaisants. »🌸",
        "🌸Sourate Ash-Shura (42:37): « Ceux qui évitent les grands péchés, les turpitudes et qui, lorsqu'ils se mettent en colère, pardonnent. »🌸",
        "🌸Sourate Al-A'raf (7:199): « Accepte ce qu'on t'offre de raisonnable, ordonne le convenable et éloigne-toi des ignorants. »🌸",
        "🌸Sourate Fussilat (41:34): « La bonne action et la mauvaise ne sont pas pareilles. Repousse (le mal) par ce qui est meilleur, et voilà que celui avec qui tu avais une animosité devient tel un ami chaleureux. »🌸",
        "🌸Sourate Al-Furqan (25:63): « Les serviteurs du Tout Miséricordieux sont ceux qui marchent humblement sur terre, et qui, lorsque les ignorants s'adressent à eux, disent : “Paix”. »🌸",
        "🌸Sourate An-Nahl (16:126): « Si vous punissez, infligez une punition équivalente à ce qu'on vous a fait. Mais si vous endurez, cela est certes meilleur pour ceux qui endurent. »🌸",
        "🌸Sourate Az-Zumar (39:10): « Dis : Ô Mes serviteurs qui croyez ! Craignez votre Seigneur. Ceux qui font le bien ici-bas auront une belle récompense. »🌸",
        "🌸Sourate Al-Imran (3:159): « C'est par quelque miséricorde de la part d'Allah que tu as été doux envers eux. Si tu avais été rude, dur de cœur, ils se seraient enfuis de ton entourage. »🌸",
        "🌸Sourate An-Nahl (16:90): « Certes, Allah commande l'équité, la bienfaisance et l'assistance aux proches. Il interdit la turpitude, l'acte répréhensible et la rébellion. »🌸",
        "🌸Sourate Al-Hujurat (49:10): « Les croyants ne sont que des frères. Établissez la concorde entre vos frères, et craignez Allah, afin qu'on vous fasse miséricorde. »🌸",
      ],
      Solitude:[
        "🌸Sourate Al-Baqara (2:186): « Et quand Mes serviteurs t'interrogent sur Moi, alors Je suis tout proche : Je réponds à l'appel de celui qui M'invoque quand il M'invoque. »🌸",
        "🌸Sourate Al-Hadid (57:4): « C'est Lui qui a créé les cieux et la terre en six jours puis S'est établi sur le Trône. Il sait ce qui pénètre dans la terre et ce qui en sort, ce qui descend du ciel et ce qui y monte. Et Il est avec vous où que vous soyez. »🌸",
        "🌸Sourate Yunus (10:62): « En vérité, les bien-aimés d'Allah seront à l'abri de toute crainte, et ils ne seront point affligés. »🌸",
        "🌸Sourate At-Tawbah (9:40): « Si vous ne lui portez pas secours, Allah l'a déjà secouru lorsque les mécréants l'avaient banni, et qu'il n'y avait que lui et un compagnon dans la grotte, et qu'il disait à son compagnon : 'Ne t'afflige pas, car Allah est avec nous.»🌸",
        "🌸Sourate Taha(20:46):«N'ayez pas peur! Je suis avec vous,j'entends et je vois.»🌸",
        "🌸Sourate Ar-Ra'd (13:11): « Il y a derrière chaque homme des anges qui se relaient devant lui et derrière lui, et qui le gardent par ordre d'Allah. »🌸",
        "🌸Sourate Qaf (50:16): « Nous avons effectivement créé l'homme et Nous savons ce que son âme lui suggère, et Nous sommes plus près de lui que sa veine jugulaire. »🌸",
        "🌸Sourate Al-Ankabut (29:69): « Et quant à ceux qui luttent pour Notre cause, Nous les guiderons certes sur Nos sentiers. »🌸",
        "🌸Sourate Al-Fath (48:4): « C'est Lui qui a fait descendre la quiétude dans les cœurs des croyants afin qu'ils ajoutent foi à leur foi. »🌸",
        "🌸Sourate Ad-Duha (93:3-4): « Ton Seigneur ne t'a ni abandonné ni détesté. La vie dernière t'est, certes, meilleure que la vie présente. »🌸",
      ],
      Tristesse:[
        "🌸Sourate Ash-Sharh (94:5-6): « A côté de la difficulté est, certes, une facilité. A côté de la difficulté est, certes, une facilité. »🌸",
        "🌸Sourate Al-Baqara (2:286): « Allah n'impose à aucune âme une charge supérieure à sa capacité. »🌸",
        "🌸Sourate Al-Imran (3:139): « Ne faiblissez pas et ne vous affligez pas, alors que vous êtes les supérieurs, si vous êtes croyants. »🌸",
        "🌸Sourate At-Tawbah (9:51): « Dis : Rien ne nous atteindra, sauf ce qu'Allah a prescrit pour nous. Il est notre Protecteur. »🌸",
        "🌸Sourate Yunus (10:107): « Et si Allah fait qu'un mal t'atteint, nul autre que Lui ne peut l'écarter. »🌸",
        "🌸Sourate Al-Anbiya (21:87): « Et Dhan-Nun (Jonas)… s'en alla, irrité. Il pensa que Nous n'allions pas l'éprouver. Puis il fit dans les ténèbres l'appel : 'Pas de divinité à part Toi ! Pureté à Toi ! J'ai été vraiment du nombre des injustes.' »🌸",
        "🌸Sourate Yusuf (12:87): « Ô mes fils, partez et enquérez-vous de Joseph et de son frère, et ne désespérez pas de la miséricorde d'Allah. Ce sont seulement les gens mécréants qui désespèrent de la miséricorde d'Allah. »🌸",
        "🌸Sourate Az-Zumar (39:53): « Dis : Ô Mes serviteurs qui avez commis des excès à votre propre détriment ! Ne désespérez pas de la miséricorde d'Allah. »🌸",
        "🌸Sourate Al-Baqara (2:153): « Ô vous qui avez cru ! Cherchez secours dans l'endurance et la prière. Car Allah est avec ceux qui sont patients. »🌸",
        "🌸Sourate Al-Ankabut (29:69): « Et quant à ceux qui luttent pour Notre cause, Nous les guiderons certes sur Nos sentiers. »🌸",
      ],
      Reconnaissance:[
        "🌸Sourate Ibrahim (14:7): « Et lorsque votre Seigneur proclama : 'Si vous êtes reconnaissants, très certainement J'augmenterai (Mes bienfaits) pour vous. Mais si vous êtes ingrats, Mon châtiment sera terrible.' »🌸",
        "🌸Sourate Luqman (31:12): « Nous avons certes donné à Luqmân la sagesse : 'Sois reconnaissant envers Allah'. Celui qui est reconnaissant n'est reconnaissant que pour lui-même. Quant à celui qui est ingrat… En vérité, Allah se dispense de tout, et Il est digne de louange. »🌸",
        "🌸Sourate Al-Baqara (2:152): « Souvenez-vous de Moi donc, Je Me souviendrai de vous. Remerciez-Moi et ne soyez pas ingrats envers Moi. »🌸",
        "🌸Sourate An-Nahl (16:114): « Mangez donc de ce qu'Allah vous a attribué de licite et de bon ; et soyez reconnaissants pour le bienfait d'Allah, si c'est Lui que vous adorez. »🌸",
        "🌸Sourate Al-Insan (76:9): « Nous ne vous nourrissons que pour l'agrément d'Allah. Nous n'attendons de vous ni récompense ni gratitude. »🌸",
        "🌸Sourate Saba (34:15): « Mangez de la subsistance de votre Seigneur et soyez-Lui reconnaissants : contrée excellente et Seigneur plein de pardon ! »🌸",
        "🌸Sourate Az-Zumar (39:66): « Adore plutôt Allah seul et sois parmi les reconnaissants. »🌸",
        "🌸Sourate An-Naml (27:19): « Seigneur ! Inspire-moi afin que je rende grâce pour Ton bienfait dont Tu m'as comblé ainsi que mes père et mère. »🌸",
        "🌸Sourate Al-A'raf (7:10): « Nous vous avons certes établis sur la terre et Nous y avons placé pour vous des moyens d'existence. Peu de vous êtes reconnaissants ! »🌸",
        "🌸Sourate Al-Baqara (2:172): « Ô vous qui avez cru ! Mangez des délices que Nous vous avons attribués et remerciez Allah, si c'est Lui que vous adorez. »🌸",
      ],
    }

function Choix(émotion) {
  const phrases = émotions[émotion];
  const index = Math.floor(Math.random() * phrases.length);
  document.getElementById("texte").textContent = phrases[index];
}
alert("Qu'Allah apaise votre coeur et illumine votre chemin à chaque instant!")